name: next_movie
description: A Flutter app template.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  kiwi: ^2.1.1
  shared_preferences: ^0.5.12+4
  skeleton_text: ^1.0.0
  url_launcher: ^5.7.10

dev_dependencies:
  bloc_test: ^7.1.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10+1
  lint: ^1.5.1
  test:

flutter:
  uses-material-design: true

  assets:
  - assets/graphics/icons/
  - assets/graphics/images/
  - assets/animations/
  - assets/strings/
  - assets/json/
  - assets/json/auth/

  fonts:
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Thin.ttf
        weight: 100
      - asset: assets/fonts/Lato-ThinItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Lato-Light.ttf
        weight: 300
      - asset: assets/fonts/Lato-LightItalic.ttf
        weight: 300
      - asset: assets/fonts/Lato-Regular.ttf
      - asset: assets/fonts/Lato-Italic.ttf
        style: italic
      - asset: assets/fonts/Lato-Bold.ttf
        weight: 700
      - asset: assets/fonts/Lato-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/Lato-Black.ttf
        weight: 900
      - asset: assets/fonts/Lato-BlackItalic.ttf
        weight: 900
        style: italic